import { Geist, Geist_Mono, Noto_Sans_Bengali } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/shared/Header/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const notoBangla = Noto_Sans_Bengali({
  variable: "--notoBangla",
  subsets: ["latin"],
});


const banglaFont = localFont({
  src: "../../public/fonts/LiAdorNoirrit-Bold.woff2",
  variable: "--banglaFont",
  subsets: ["latin"]
})
const banglaFontTwo = localFont({
  src: "../../public/fonts/LiAdorNoirrit-SemiBold.woff2",
  variable: "--banglaFontTwo",
  subsets: ["latin"]
})
const banglaFontThree = localFont({
  src: "../../public/fonts/LiAdorNoirrit.woff2",
  variable: "--banglaFontThree",
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoBangla.variable} ${banglaFontTwo.variable} ${banglaFont.variable} pt-16 antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
